
target 'TuSDKVideoDemo' do
  
  xcodeproj 'TuSDKVideoDemo-Refactor/TuSDKVideoDemo-Refactor.xcodeproj'
  workspace 'TuSDKFPDemo'
    # pod 'DoraemonKit/Core', '~> 3.0.4', :configurations => ['Debug']
    pod 'Masonry', '1.1.0'
    pod 'TZImagePickerController', '3.5.8'
end
